default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["lando_nogeoserver_database_conn_host"] || ENV["POSTGRES_HOST"] || "localhost" %>
  port: <%= ENV["lando_nogeoserver_database_conn_port"] || ENV["POSTGRES_PORT"] ||  5432 %>
  username: <%= ENV["lando_nogeoserver_database_creds_user"] || ENV["POSTGRES_USER"] %>
  password: <%= ENV["lando_nogeoserver_database_creds_password"] || ENV["POSTGRES_PASSWORD"] %>
  database: <%= ENV['POSTGRES_DB'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nogeoserver_development

test:
  <<: *default
  database: nogeoserver_test

production:
  <<: *default
